import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Chat from "../components/Chat";
import Player from "../components/Player";
import TopBar from "../components/TopBar";
import UrlInput from "../components/UrlInput";
import { useQuery, withWunderGraph } from "../components/generated/nextjs";

const Home: NextPage = () => {
  const [url, setUrl] = useState<String>(
    "https://music.youtube.com/watch?v=nkvg9c9oczM"
  );
  const [id, setId] = useState<String>();

  useEffect(() => {
    if (!url.indexOf("?v=")) return;

    const params = url.indexOf("?v=") + 3;
    const id = url.substring(params);
    setId(id);
  }, [url]);

  return (
    <div className="flex flex-col w-full h-full text-white bg-black">
      <Head>
        <title>YT-Hut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <TopBar />
      <UrlInput setUrl={setUrl} />
      <div className="flex flex-row justify-around p-5 w-full h-screen">
        {id && (
          <>
            <Player id={id} />
            <Chat id={id} />
          </>
        )}
        {!id && <div className="text-4xl">Invalid Video URL</div>}
      </div>
    </div>
  );
};

export default withWunderGraph(Home);
